// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatMessages
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public enum Payload : byte
{
  NONE = 0,
  JoinRequest = 1,
  JoinResult = 2,
  Start = 3,
  SetCharacter = 4,
  PlayerList = 5,
  TimeRemaining = 6,
  Shutdown = 7,
  ReplayFrom = 8,
  SaveHash = 9,
  InvalidHash = 10,
  TimeFromStart = 11,
  GameOver = 12,
};

public struct JoinResult : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static JoinResult GetRootAsJoinResult(ByteBuffer _bb) { return GetRootAsJoinResult(_bb, new JoinResult()); }
  public static JoinResult GetRootAsJoinResult(ByteBuffer _bb, JoinResult obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JoinResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Value { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string Reason { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetReasonBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetReasonBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetReasonArray() { return __p.__vector_as_array<byte>(6); }
  public byte Slot { get { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<FlatMessages.JoinResult> CreateJoinResult(FlatBufferBuilder builder,
      bool value = false,
      StringOffset reasonOffset = default(StringOffset),
      byte slot = 0) {
    builder.StartTable(3);
    JoinResult.AddReason(builder, reasonOffset);
    JoinResult.AddSlot(builder, slot);
    JoinResult.AddValue(builder, value);
    return JoinResult.EndJoinResult(builder);
  }

  public static void StartJoinResult(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddValue(FlatBufferBuilder builder, bool value) { builder.AddBool(0, value, false); }
  public static void AddReason(FlatBufferBuilder builder, StringOffset reasonOffset) { builder.AddOffset(1, reasonOffset.Value, 0); }
  public static void AddSlot(FlatBufferBuilder builder, byte slot) { builder.AddByte(2, slot, 0); }
  public static Offset<FlatMessages.JoinResult> EndJoinResult(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatMessages.JoinResult>(o);
  }
};

public struct Start : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Start __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Value { get { return 0!=__p.bb.Get(__p.bb_pos + 0); } }
  public uint Seed { get { return __p.bb.GetUint(__p.bb_pos + 4); } }

  public static Offset<FlatMessages.Start> CreateStart(FlatBufferBuilder builder, bool Value, uint Seed) {
    builder.Prep(4, 8);
    builder.PutUint(Seed);
    builder.Pad(3);
    builder.PutBool(Value);
    return new Offset<FlatMessages.Start>(builder.Offset);
  }
};

public struct Shutdown : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Shutdown __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Value { get { return 0!=__p.bb.Get(__p.bb_pos + 0); } }

  public static Offset<FlatMessages.Shutdown> CreateShutdown(FlatBufferBuilder builder, bool Value) {
    builder.Prep(1, 1);
    builder.PutBool(Value);
    return new Offset<FlatMessages.Shutdown>(builder.Offset);
  }
};

public struct SetCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static SetCharacter GetRootAsSetCharacter(ByteBuffer _bb) { return GetRootAsSetCharacter(_bb, new SetCharacter()); }
  public static SetCharacter GetRootAsSetCharacter(ByteBuffer _bb, SetCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string PlayerId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPlayerIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetPlayerIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetPlayerIdArray() { return __p.__vector_as_array<byte>(4); }
  public string Character { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCharacterBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetCharacterBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetCharacterArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<FlatMessages.SetCharacter> CreateSetCharacter(FlatBufferBuilder builder,
      StringOffset player_idOffset = default(StringOffset),
      StringOffset characterOffset = default(StringOffset)) {
    builder.StartTable(2);
    SetCharacter.AddCharacter(builder, characterOffset);
    SetCharacter.AddPlayerId(builder, player_idOffset);
    return SetCharacter.EndSetCharacter(builder);
  }

  public static void StartSetCharacter(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPlayerId(FlatBufferBuilder builder, StringOffset playerIdOffset) { builder.AddOffset(0, playerIdOffset.Value, 0); }
  public static void AddCharacter(FlatBufferBuilder builder, StringOffset characterOffset) { builder.AddOffset(1, characterOffset.Value, 0); }
  public static Offset<FlatMessages.SetCharacter> EndSetCharacter(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatMessages.SetCharacter>(o);
  }
};

public struct JoinRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static JoinRequest GetRootAsJoinRequest(ByteBuffer _bb) { return GetRootAsJoinRequest(_bb, new JoinRequest()); }
  public static JoinRequest GetRootAsJoinRequest(ByteBuffer _bb, JoinRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JoinRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sbyte GameType { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
  public string Json { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetJsonBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetJsonBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetJsonArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<FlatMessages.JoinRequest> CreateJoinRequest(FlatBufferBuilder builder,
      sbyte game_type = 0,
      StringOffset jsonOffset = default(StringOffset)) {
    builder.StartTable(2);
    JoinRequest.AddJson(builder, jsonOffset);
    JoinRequest.AddGameType(builder, game_type);
    return JoinRequest.EndJoinRequest(builder);
  }

  public static void StartJoinRequest(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddGameType(FlatBufferBuilder builder, sbyte gameType) { builder.AddSbyte(0, gameType, 0); }
  public static void AddJson(FlatBufferBuilder builder, StringOffset jsonOffset) { builder.AddOffset(1, jsonOffset.Value, 0); }
  public static Offset<FlatMessages.JoinRequest> EndJoinRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatMessages.JoinRequest>(o);
  }
};

public struct Player : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Player GetRootAsPlayer(ByteBuffer _bb) { return GetRootAsPlayer(_bb, new Player()); }
  public static Player GetRootAsPlayer(ByteBuffer _bb, Player obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Player __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetIdArray() { return __p.__vector_as_array<byte>(4); }
  public byte Slot { get { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public string Nickname { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNicknameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetNicknameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetNicknameArray() { return __p.__vector_as_array<byte>(8); }
  public string Character { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCharacterBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetCharacterBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetCharacterArray() { return __p.__vector_as_array<byte>(10); }
  public string Icon { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIconBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetIconBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetIconArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<FlatMessages.Player> CreatePlayer(FlatBufferBuilder builder,
      StringOffset idOffset = default(StringOffset),
      byte slot = 0,
      StringOffset nicknameOffset = default(StringOffset),
      StringOffset characterOffset = default(StringOffset),
      StringOffset iconOffset = default(StringOffset)) {
    builder.StartTable(5);
    Player.AddIcon(builder, iconOffset);
    Player.AddCharacter(builder, characterOffset);
    Player.AddNickname(builder, nicknameOffset);
    Player.AddId(builder, idOffset);
    Player.AddSlot(builder, slot);
    return Player.EndPlayer(builder);
  }

  public static void StartPlayer(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddId(FlatBufferBuilder builder, StringOffset idOffset) { builder.AddOffset(0, idOffset.Value, 0); }
  public static void AddSlot(FlatBufferBuilder builder, byte slot) { builder.AddByte(1, slot, 0); }
  public static void AddNickname(FlatBufferBuilder builder, StringOffset nicknameOffset) { builder.AddOffset(2, nicknameOffset.Value, 0); }
  public static void AddCharacter(FlatBufferBuilder builder, StringOffset characterOffset) { builder.AddOffset(3, characterOffset.Value, 0); }
  public static void AddIcon(FlatBufferBuilder builder, StringOffset iconOffset) { builder.AddOffset(4, iconOffset.Value, 0); }
  public static Offset<FlatMessages.Player> EndPlayer(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatMessages.Player>(o);
  }
};

public struct PlayerList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static PlayerList GetRootAsPlayerList(ByteBuffer _bb) { return GetRootAsPlayerList(_bb, new PlayerList()); }
  public static PlayerList GetRootAsPlayerList(ByteBuffer _bb, PlayerList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatMessages.Player? Players(int j) { int o = __p.__offset(4); return o != 0 ? (FlatMessages.Player?)(new FlatMessages.Player()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int PlayersLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<FlatMessages.PlayerList> CreatePlayerList(FlatBufferBuilder builder,
      VectorOffset playersOffset = default(VectorOffset)) {
    builder.StartTable(1);
    PlayerList.AddPlayers(builder, playersOffset);
    return PlayerList.EndPlayerList(builder);
  }

  public static void StartPlayerList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPlayers(FlatBufferBuilder builder, VectorOffset playersOffset) { builder.AddOffset(0, playersOffset.Value, 0); }
  public static VectorOffset CreatePlayersVector(FlatBufferBuilder builder, Offset<FlatMessages.Player>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreatePlayersVectorBlock(FlatBufferBuilder builder, Offset<FlatMessages.Player>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartPlayersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FlatMessages.PlayerList> EndPlayerList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatMessages.PlayerList>(o);
  }
};

public struct TimeRemaining : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static TimeRemaining GetRootAsTimeRemaining(ByteBuffer _bb) { return GetRootAsTimeRemaining(_bb, new TimeRemaining()); }
  public static TimeRemaining GetRootAsTimeRemaining(ByteBuffer _bb, TimeRemaining obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TimeRemaining __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Value { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string State { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetStateBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetStateBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetStateArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<FlatMessages.TimeRemaining> CreateTimeRemaining(FlatBufferBuilder builder,
      uint value = 0,
      StringOffset stateOffset = default(StringOffset)) {
    builder.StartTable(2);
    TimeRemaining.AddState(builder, stateOffset);
    TimeRemaining.AddValue(builder, value);
    return TimeRemaining.EndTimeRemaining(builder);
  }

  public static void StartTimeRemaining(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddValue(FlatBufferBuilder builder, uint value) { builder.AddUint(0, value, 0); }
  public static void AddState(FlatBufferBuilder builder, StringOffset stateOffset) { builder.AddOffset(1, stateOffset.Value, 0); }
  public static Offset<FlatMessages.TimeRemaining> EndTimeRemaining(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatMessages.TimeRemaining>(o);
  }
};

public struct ReplayFrom : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ReplayFrom GetRootAsReplayFrom(ByteBuffer _bb) { return GetRootAsReplayFrom(_bb, new ReplayFrom()); }
  public static ReplayFrom GetRootAsReplayFrom(ByteBuffer _bb, ReplayFrom obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ReplayFrom __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint LastTick { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<FlatMessages.ReplayFrom> CreateReplayFrom(FlatBufferBuilder builder,
      uint last_tick = 0) {
    builder.StartTable(1);
    ReplayFrom.AddLastTick(builder, last_tick);
    return ReplayFrom.EndReplayFrom(builder);
  }

  public static void StartReplayFrom(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddLastTick(FlatBufferBuilder builder, uint lastTick) { builder.AddUint(0, lastTick, 0); }
  public static Offset<FlatMessages.ReplayFrom> EndReplayFrom(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatMessages.ReplayFrom>(o);
  }
};

public struct SaveHash : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static SaveHash GetRootAsSaveHash(ByteBuffer _bb) { return GetRootAsSaveHash(_bb, new SaveHash()); }
  public static SaveHash GetRootAsSaveHash(ByteBuffer _bb, SaveHash obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SaveHash __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Tick { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public int Hash { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<FlatMessages.SaveHash> CreateSaveHash(FlatBufferBuilder builder,
      uint tick = 0,
      int hash = 0) {
    builder.StartTable(2);
    SaveHash.AddHash(builder, hash);
    SaveHash.AddTick(builder, tick);
    return SaveHash.EndSaveHash(builder);
  }

  public static void StartSaveHash(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddTick(FlatBufferBuilder builder, uint tick) { builder.AddUint(0, tick, 0); }
  public static void AddHash(FlatBufferBuilder builder, int hash) { builder.AddInt(1, hash, 0); }
  public static Offset<FlatMessages.SaveHash> EndSaveHash(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatMessages.SaveHash>(o);
  }
};

public struct InvalidHash : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static InvalidHash GetRootAsInvalidHash(ByteBuffer _bb) { return GetRootAsInvalidHash(_bb, new InvalidHash()); }
  public static InvalidHash GetRootAsInvalidHash(ByteBuffer _bb, InvalidHash obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public InvalidHash __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Tick { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<FlatMessages.InvalidHash> CreateInvalidHash(FlatBufferBuilder builder,
      uint tick = 0) {
    builder.StartTable(1);
    InvalidHash.AddTick(builder, tick);
    return InvalidHash.EndInvalidHash(builder);
  }

  public static void StartInvalidHash(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTick(FlatBufferBuilder builder, uint tick) { builder.AddUint(0, tick, 0); }
  public static Offset<FlatMessages.InvalidHash> EndInvalidHash(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatMessages.InvalidHash>(o);
  }
};

public struct TimeFromStart : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static TimeFromStart GetRootAsTimeFromStart(ByteBuffer _bb) { return GetRootAsTimeFromStart(_bb, new TimeFromStart()); }
  public static TimeFromStart GetRootAsTimeFromStart(ByteBuffer _bb, TimeFromStart obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TimeFromStart __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Time { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<FlatMessages.TimeFromStart> CreateTimeFromStart(FlatBufferBuilder builder,
      uint time = 0) {
    builder.StartTable(1);
    TimeFromStart.AddTime(builder, time);
    return TimeFromStart.EndTimeFromStart(builder);
  }

  public static void StartTimeFromStart(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTime(FlatBufferBuilder builder, uint time) { builder.AddUint(0, time, 0); }
  public static Offset<FlatMessages.TimeFromStart> EndTimeFromStart(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatMessages.TimeFromStart>(o);
  }
};

public struct Stats : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Stats GetRootAsStats(ByteBuffer _bb) { return GetRootAsStats(_bb, new Stats()); }
  public static Stats GetRootAsStats(ByteBuffer _bb, Stats obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Stats __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Kills { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Deaths { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Id { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIdBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetIdArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<FlatMessages.Stats> CreateStats(FlatBufferBuilder builder,
      uint kills = 0,
      uint deaths = 0,
      StringOffset idOffset = default(StringOffset)) {
    builder.StartTable(3);
    Stats.AddId(builder, idOffset);
    Stats.AddDeaths(builder, deaths);
    Stats.AddKills(builder, kills);
    return Stats.EndStats(builder);
  }

  public static void StartStats(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddKills(FlatBufferBuilder builder, uint kills) { builder.AddUint(0, kills, 0); }
  public static void AddDeaths(FlatBufferBuilder builder, uint deaths) { builder.AddUint(1, deaths, 0); }
  public static void AddId(FlatBufferBuilder builder, StringOffset idOffset) { builder.AddOffset(2, idOffset.Value, 0); }
  public static Offset<FlatMessages.Stats> EndStats(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatMessages.Stats>(o);
  }
};

public struct GameOver : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static GameOver GetRootAsGameOver(ByteBuffer _bb) { return GetRootAsGameOver(_bb, new GameOver()); }
  public static GameOver GetRootAsGameOver(ByteBuffer _bb, GameOver obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GameOver __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Winner { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetWinnerBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetWinnerBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetWinnerArray() { return __p.__vector_as_array<byte>(4); }
  public int Hash { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public FlatMessages.Stats? Stats(int j) { int o = __p.__offset(8); return o != 0 ? (FlatMessages.Stats?)(new FlatMessages.Stats()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int StatsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<FlatMessages.GameOver> CreateGameOver(FlatBufferBuilder builder,
      StringOffset winnerOffset = default(StringOffset),
      int hash = 0,
      VectorOffset statsOffset = default(VectorOffset)) {
    builder.StartTable(3);
    GameOver.AddStats(builder, statsOffset);
    GameOver.AddHash(builder, hash);
    GameOver.AddWinner(builder, winnerOffset);
    return GameOver.EndGameOver(builder);
  }

  public static void StartGameOver(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddWinner(FlatBufferBuilder builder, StringOffset winnerOffset) { builder.AddOffset(0, winnerOffset.Value, 0); }
  public static void AddHash(FlatBufferBuilder builder, int hash) { builder.AddInt(1, hash, 0); }
  public static void AddStats(FlatBufferBuilder builder, VectorOffset statsOffset) { builder.AddOffset(2, statsOffset.Value, 0); }
  public static VectorOffset CreateStatsVector(FlatBufferBuilder builder, Offset<FlatMessages.Stats>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateStatsVectorBlock(FlatBufferBuilder builder, Offset<FlatMessages.Stats>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartStatsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FlatMessages.GameOver> EndGameOver(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatMessages.GameOver>(o);
  }
};

public struct SystemMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static SystemMessage GetRootAsSystemMessage(ByteBuffer _bb) { return GetRootAsSystemMessage(_bb, new SystemMessage()); }
  public static SystemMessage GetRootAsSystemMessage(ByteBuffer _bb, SystemMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SystemMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Timestamp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public FlatMessages.Payload PayloadType { get { int o = __p.__offset(6); return o != 0 ? (FlatMessages.Payload)__p.bb.Get(o + __p.bb_pos) : FlatMessages.Payload.NONE; } }
  public TTable? Payload<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(8); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public FlatMessages.JoinRequest PayloadAsJoinRequest() { return Payload<FlatMessages.JoinRequest>().Value; }
  public FlatMessages.JoinResult PayloadAsJoinResult() { return Payload<FlatMessages.JoinResult>().Value; }
  public FlatMessages.Start PayloadAsStart() { return Payload<FlatMessages.Start>().Value; }
  public FlatMessages.SetCharacter PayloadAsSetCharacter() { return Payload<FlatMessages.SetCharacter>().Value; }
  public FlatMessages.PlayerList PayloadAsPlayerList() { return Payload<FlatMessages.PlayerList>().Value; }
  public FlatMessages.TimeRemaining PayloadAsTimeRemaining() { return Payload<FlatMessages.TimeRemaining>().Value; }
  public FlatMessages.Shutdown PayloadAsShutdown() { return Payload<FlatMessages.Shutdown>().Value; }
  public FlatMessages.ReplayFrom PayloadAsReplayFrom() { return Payload<FlatMessages.ReplayFrom>().Value; }
  public FlatMessages.SaveHash PayloadAsSaveHash() { return Payload<FlatMessages.SaveHash>().Value; }
  public FlatMessages.InvalidHash PayloadAsInvalidHash() { return Payload<FlatMessages.InvalidHash>().Value; }
  public FlatMessages.TimeFromStart PayloadAsTimeFromStart() { return Payload<FlatMessages.TimeFromStart>().Value; }
  public FlatMessages.GameOver PayloadAsGameOver() { return Payload<FlatMessages.GameOver>().Value; }

  public static Offset<FlatMessages.SystemMessage> CreateSystemMessage(FlatBufferBuilder builder,
      uint timestamp = 0,
      FlatMessages.Payload payload_type = FlatMessages.Payload.NONE,
      int payloadOffset = 0) {
    builder.StartTable(3);
    SystemMessage.AddPayload(builder, payloadOffset);
    SystemMessage.AddTimestamp(builder, timestamp);
    SystemMessage.AddPayloadType(builder, payload_type);
    return SystemMessage.EndSystemMessage(builder);
  }

  public static void StartSystemMessage(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddTimestamp(FlatBufferBuilder builder, uint timestamp) { builder.AddUint(0, timestamp, 0); }
  public static void AddPayloadType(FlatBufferBuilder builder, FlatMessages.Payload payloadType) { builder.AddByte(1, (byte)payloadType, 0); }
  public static void AddPayload(FlatBufferBuilder builder, int payloadOffset) { builder.AddOffset(2, payloadOffset, 0); }
  public static Offset<FlatMessages.SystemMessage> EndSystemMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatMessages.SystemMessage>(o);
  }
};


}
