// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SerializedMessages
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public enum Payload : byte
{
  NONE = 0,
  JoinRequest = 1,
  JoinResult = 2,
  Start = 3,
  SetCharacter = 4,
  PlayerList = 5,
  TimeRemaining = 6,
  Shutdown = 7,
};

public struct JoinResult : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static JoinResult GetRootAsJoinResult(ByteBuffer _bb) { return GetRootAsJoinResult(_bb, new JoinResult()); }
  public static JoinResult GetRootAsJoinResult(ByteBuffer _bb, JoinResult obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JoinResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Value { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string Reason { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetReasonBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetReasonBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetReasonArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<SerializedMessages.JoinResult> CreateJoinResult(FlatBufferBuilder builder,
      bool value = false,
      StringOffset reasonOffset = default(StringOffset)) {
    builder.StartTable(2);
    JoinResult.AddReason(builder, reasonOffset);
    JoinResult.AddValue(builder, value);
    return JoinResult.EndJoinResult(builder);
  }

  public static void StartJoinResult(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddValue(FlatBufferBuilder builder, bool value) { builder.AddBool(0, value, false); }
  public static void AddReason(FlatBufferBuilder builder, StringOffset reasonOffset) { builder.AddOffset(1, reasonOffset.Value, 0); }
  public static Offset<SerializedMessages.JoinResult> EndJoinResult(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SerializedMessages.JoinResult>(o);
  }
};

public struct Start : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Start __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Value { get { return 0!=__p.bb.Get(__p.bb_pos + 0); } }

  public static Offset<SerializedMessages.Start> CreateStart(FlatBufferBuilder builder, bool Value) {
    builder.Prep(1, 1);
    builder.PutBool(Value);
    return new Offset<SerializedMessages.Start>(builder.Offset);
  }
};

public struct Shutdown : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Shutdown __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Value { get { return 0!=__p.bb.Get(__p.bb_pos + 0); } }

  public static Offset<SerializedMessages.Shutdown> CreateShutdown(FlatBufferBuilder builder, bool Value) {
    builder.Prep(1, 1);
    builder.PutBool(Value);
    return new Offset<SerializedMessages.Shutdown>(builder.Offset);
  }
};

public struct SetCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static SetCharacter GetRootAsSetCharacter(ByteBuffer _bb) { return GetRootAsSetCharacter(_bb, new SetCharacter()); }
  public static SetCharacter GetRootAsSetCharacter(ByteBuffer _bb, SetCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string PlayerId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPlayerIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetPlayerIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetPlayerIdArray() { return __p.__vector_as_array<byte>(4); }
  public string Character { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCharacterBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetCharacterBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetCharacterArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<SerializedMessages.SetCharacter> CreateSetCharacter(FlatBufferBuilder builder,
      StringOffset player_idOffset = default(StringOffset),
      StringOffset characterOffset = default(StringOffset)) {
    builder.StartTable(2);
    SetCharacter.AddCharacter(builder, characterOffset);
    SetCharacter.AddPlayerId(builder, player_idOffset);
    return SetCharacter.EndSetCharacter(builder);
  }

  public static void StartSetCharacter(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPlayerId(FlatBufferBuilder builder, StringOffset playerIdOffset) { builder.AddOffset(0, playerIdOffset.Value, 0); }
  public static void AddCharacter(FlatBufferBuilder builder, StringOffset characterOffset) { builder.AddOffset(1, characterOffset.Value, 0); }
  public static Offset<SerializedMessages.SetCharacter> EndSetCharacter(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SerializedMessages.SetCharacter>(o);
  }
};

public struct JoinRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static JoinRequest GetRootAsJoinRequest(ByteBuffer _bb) { return GetRootAsJoinRequest(_bb, new JoinRequest()); }
  public static JoinRequest GetRootAsJoinRequest(ByteBuffer _bb, JoinRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JoinRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Json { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetJsonBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetJsonBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetJsonArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<SerializedMessages.JoinRequest> CreateJoinRequest(FlatBufferBuilder builder,
      StringOffset jsonOffset = default(StringOffset)) {
    builder.StartTable(1);
    JoinRequest.AddJson(builder, jsonOffset);
    return JoinRequest.EndJoinRequest(builder);
  }

  public static void StartJoinRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddJson(FlatBufferBuilder builder, StringOffset jsonOffset) { builder.AddOffset(0, jsonOffset.Value, 0); }
  public static Offset<SerializedMessages.JoinRequest> EndJoinRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SerializedMessages.JoinRequest>(o);
  }
};

public struct Player : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Player GetRootAsPlayer(ByteBuffer _bb) { return GetRootAsPlayer(_bb, new Player()); }
  public static Player GetRootAsPlayer(ByteBuffer _bb, Player obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Player __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetIdArray() { return __p.__vector_as_array<byte>(4); }
  public byte Slot { get { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public string Nickname { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNicknameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetNicknameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetNicknameArray() { return __p.__vector_as_array<byte>(8); }
  public string Character { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCharacterBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetCharacterBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetCharacterArray() { return __p.__vector_as_array<byte>(10); }
  public string Icon { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIconBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetIconBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetIconArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<SerializedMessages.Player> CreatePlayer(FlatBufferBuilder builder,
      StringOffset idOffset = default(StringOffset),
      byte slot = 0,
      StringOffset nicknameOffset = default(StringOffset),
      StringOffset characterOffset = default(StringOffset),
      StringOffset iconOffset = default(StringOffset)) {
    builder.StartTable(5);
    Player.AddIcon(builder, iconOffset);
    Player.AddCharacter(builder, characterOffset);
    Player.AddNickname(builder, nicknameOffset);
    Player.AddId(builder, idOffset);
    Player.AddSlot(builder, slot);
    return Player.EndPlayer(builder);
  }

  public static void StartPlayer(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddId(FlatBufferBuilder builder, StringOffset idOffset) { builder.AddOffset(0, idOffset.Value, 0); }
  public static void AddSlot(FlatBufferBuilder builder, byte slot) { builder.AddByte(1, slot, 0); }
  public static void AddNickname(FlatBufferBuilder builder, StringOffset nicknameOffset) { builder.AddOffset(2, nicknameOffset.Value, 0); }
  public static void AddCharacter(FlatBufferBuilder builder, StringOffset characterOffset) { builder.AddOffset(3, characterOffset.Value, 0); }
  public static void AddIcon(FlatBufferBuilder builder, StringOffset iconOffset) { builder.AddOffset(4, iconOffset.Value, 0); }
  public static Offset<SerializedMessages.Player> EndPlayer(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SerializedMessages.Player>(o);
  }
};

public struct PlayerList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static PlayerList GetRootAsPlayerList(ByteBuffer _bb) { return GetRootAsPlayerList(_bb, new PlayerList()); }
  public static PlayerList GetRootAsPlayerList(ByteBuffer _bb, PlayerList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SerializedMessages.Player? Players(int j) { int o = __p.__offset(4); return o != 0 ? (SerializedMessages.Player?)(new SerializedMessages.Player()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int PlayersLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<SerializedMessages.PlayerList> CreatePlayerList(FlatBufferBuilder builder,
      VectorOffset playersOffset = default(VectorOffset)) {
    builder.StartTable(1);
    PlayerList.AddPlayers(builder, playersOffset);
    return PlayerList.EndPlayerList(builder);
  }

  public static void StartPlayerList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPlayers(FlatBufferBuilder builder, VectorOffset playersOffset) { builder.AddOffset(0, playersOffset.Value, 0); }
  public static VectorOffset CreatePlayersVector(FlatBufferBuilder builder, Offset<SerializedMessages.Player>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreatePlayersVectorBlock(FlatBufferBuilder builder, Offset<SerializedMessages.Player>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartPlayersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SerializedMessages.PlayerList> EndPlayerList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SerializedMessages.PlayerList>(o);
  }
};

public struct TimeRemaining : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static TimeRemaining GetRootAsTimeRemaining(ByteBuffer _bb) { return GetRootAsTimeRemaining(_bb, new TimeRemaining()); }
  public static TimeRemaining GetRootAsTimeRemaining(ByteBuffer _bb, TimeRemaining obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TimeRemaining __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Value { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<SerializedMessages.TimeRemaining> CreateTimeRemaining(FlatBufferBuilder builder,
      uint value = 0) {
    builder.StartTable(1);
    TimeRemaining.AddValue(builder, value);
    return TimeRemaining.EndTimeRemaining(builder);
  }

  public static void StartTimeRemaining(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddValue(FlatBufferBuilder builder, uint value) { builder.AddUint(0, value, 0); }
  public static Offset<SerializedMessages.TimeRemaining> EndTimeRemaining(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SerializedMessages.TimeRemaining>(o);
  }
};

public struct SystemMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static SystemMessage GetRootAsSystemMessage(ByteBuffer _bb) { return GetRootAsSystemMessage(_bb, new SystemMessage()); }
  public static SystemMessage GetRootAsSystemMessage(ByteBuffer _bb, SystemMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SystemMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Timestamp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public SerializedMessages.Payload PayloadType { get { int o = __p.__offset(6); return o != 0 ? (SerializedMessages.Payload)__p.bb.Get(o + __p.bb_pos) : SerializedMessages.Payload.NONE; } }
  public TTable? Payload<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(8); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public SerializedMessages.JoinRequest PayloadAsJoinRequest() { return Payload<SerializedMessages.JoinRequest>().Value; }
  public SerializedMessages.JoinResult PayloadAsJoinResult() { return Payload<SerializedMessages.JoinResult>().Value; }
  public SerializedMessages.Start PayloadAsStart() { return Payload<SerializedMessages.Start>().Value; }
  public SerializedMessages.SetCharacter PayloadAsSetCharacter() { return Payload<SerializedMessages.SetCharacter>().Value; }
  public SerializedMessages.PlayerList PayloadAsPlayerList() { return Payload<SerializedMessages.PlayerList>().Value; }
  public SerializedMessages.TimeRemaining PayloadAsTimeRemaining() { return Payload<SerializedMessages.TimeRemaining>().Value; }
  public SerializedMessages.Shutdown PayloadAsShutdown() { return Payload<SerializedMessages.Shutdown>().Value; }

  public static Offset<SerializedMessages.SystemMessage> CreateSystemMessage(FlatBufferBuilder builder,
      uint timestamp = 0,
      SerializedMessages.Payload payload_type = SerializedMessages.Payload.NONE,
      int payloadOffset = 0) {
    builder.StartTable(3);
    SystemMessage.AddPayload(builder, payloadOffset);
    SystemMessage.AddTimestamp(builder, timestamp);
    SystemMessage.AddPayloadType(builder, payload_type);
    return SystemMessage.EndSystemMessage(builder);
  }

  public static void StartSystemMessage(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddTimestamp(FlatBufferBuilder builder, uint timestamp) { builder.AddUint(0, timestamp, 0); }
  public static void AddPayloadType(FlatBufferBuilder builder, SerializedMessages.Payload payloadType) { builder.AddByte(1, (byte)payloadType, 0); }
  public static void AddPayload(FlatBufferBuilder builder, int payloadOffset) { builder.AddOffset(2, payloadOffset, 0); }
  public static Offset<SerializedMessages.SystemMessage> EndSystemMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SerializedMessages.SystemMessage>(o);
  }
};


}
